name: Lint

on:
  push:
    paths:
      - '**/*.py'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Disable git SSL verification
      run: git config --global http.sslVerify false

    - uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: flake8 Lint
      uses: py-actions/flake8@v2
